if (DECAY)
	set (DECAY_VAL ${DECAY})
else()
	set (DECAY_VAL 1)
endif()
if (BONUS)
	set (BONUS_VAL ${BONUS})
else()
	set (BONUS_VAL ${DECAY_VAL})
endif()

if (LUBY_BASE)
	set (LUBY_BASE_VAL ${LUBY_BASE})
else()
	set (LUBY_BASE_VAL 2)
endif()

if(LUBY_INCR)
	set (LUBY_INCR_VAL ${LUBY_INCR})
else()
	set (LUBY_INCR_VAL 100)
endif()

if (COSTANT)
	set (COSTANT_MODE 1)
	set (MAX_CONF ${COSTANT})
endif()
